import { Character } from './types';

export const characters: Character[] = [
  { name: 'Albert Einstein', image: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Albert_Einstein_Head.jpg' },
  { name: 'Frida Kahlo', image: 'https://upload.wikimedia.org/wikipedia/commons/0/06/Frida_Kahlo%2C_by_Guillermo_Kahlo.jpg' },
  { name: 'Leonardo da Vinci', image: 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Leonardo_self.jpg' },
  { name: 'Marie Curie', image: 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Marie_Curie_c1920.jpg' },
  { name: 'Nelson Mandela', image: 'https://upload.wikimedia.org/wikipedia/commons/0/02/Nelson_Mandela_1994.jpg' },
  { name: 'Cleopatra', image: 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Cleopatra_VII_bust.jpg' },
  { name: 'Abraham Lincoln', image: 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Abraham_Lincoln_O-77_matte_collodion_print.jpg' },
  { name: 'Gandhi', image: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Mahatma-Gandhi%2C_studio%2C_1931.jpg' },
  { name: 'William Shakespeare', image: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Shakespeare.jpg' },
  { name: 'Pablo Picasso', image: 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Portrait_de_Picasso%2C_1908.jpg' },
  { name: 'Mozart', image: 'https://upload.wikimedia.org/wikipedia/commons/1/1e/Wolfgang-amadeus-mozart_1.jpg' },
  { name: 'Beethoven', image: 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Beethoven.jpg' },
  { name: 'Michael Jordan', image: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Michael_Jordan_in_2014.jpg' },
  { name: 'Pelé', image: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Pele_con_brasil.jpg' },
  { name: 'Muhammad Ali', image: 'https://upload.wikimedia.org/wikipedia/commons/8/89/Muhammad_Ali_NYWTS.jpg' },
  { name: 'Serena Williams', image: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Serena_Williams_at_2013_US_Open.jpg' },
  { name: 'Steve Jobs', image: 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Steve_Jobs_Headshot_2010-CROP_%28cropped_2%29.jpg' },
  { name: 'Bill Gates', image: 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Bill_Gates_2017_%28cropped%29.jpg' },
  { name: 'Elon Musk', image: 'https://upload.wikimedia.org/wikipedia/commons/3/34/Elon_Musk_Royal_Society_%28crop2%29.jpg' },
  { name: 'Mark Zuckerberg', image: 'https://upload.wikimedia.org/wikipedia/commons/1/18/Mark_Zuckerberg_F8_2019_Keynote_%2832830578717%29_%28cropped%29.jpg' },
  { name: 'Harry Potter', image: 'https://upload.wikimedia.org/wikipedia/en/d/d7/Harry_Potter_character_poster.jpg' },
  { name: 'Spider-Man', image: 'https://upload.wikimedia.org/wikipedia/en/2/21/Web_of_Spider-Man_Vol_1_129-1.png' },
  { name: 'Batman', image: 'https://upload.wikimedia.org/wikipedia/en/1/19/Batman_%28circa_2016%29.png' },
  { name: 'Superman', image: 'https://upload.wikimedia.org/wikipedia/en/3/35/Supermanflying.png' },
  { name: 'Mickey Mouse', image: 'https://upload.wikimedia.org/wikipedia/en/d/d4/Mickey_Mouse.png' },
  { name: 'Mario Bros', image: 'https://upload.wikimedia.org/wikipedia/en/a/a9/MarioCharacter.png' },
  { name: 'Pikachu', image: 'https://upload.wikimedia.org/wikipedia/en/a/a6/Pok%C3%A9mon_Pikachu_art.png' },
  { name: 'Sonic', image: 'https://upload.wikimedia.org/wikipedia/en/c/c8/Sonic_the_Hedgehog_character_artwork.png' },
  { name: 'Cristiano Ronaldo', image: 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Cristiano_Ronaldo_2018.jpg' },
  { name: 'Lionel Messi', image: 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Lionel-Messi-Argentina-2022-FIFA-World-Cup_%28cropped%29.jpg' },
  { name: 'The Beatles', image: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Beatles_ad_1965_just_the_beatles_crop.jpg' },
  { name: 'Elvis Presley', image: 'https://upload.wikimedia.org/wikipedia/commons/9/99/Elvis_Presley_promoting_Jailhouse_Rock.jpg' },
  { name: 'Donald Trump', image: 'https://upload.wikimedia.org/wikipedia/commons/5/56/Donald_Trump_official_portrait.jpg' },
  { name: 'Barack Obama', image: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/President_Barack_Obama.jpg' },
  { name: 'Roberto Hernández Jr.', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/300px-No_image_available.svg.png' },
  { name: 'Chespirito', image: 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Chespirito_2012.jpg' },
  { name: 'Cantinflas', image: 'https://upload.wikimedia.org/wikipedia/commons/7/73/Cantinflas-publicity.jpg' },
  { name: 'Maluma', image: 'https://upload.wikimedia.org/wikipedia/commons/4/49/Maluma_2019_by_Glenn_Francis.jpg' },
  { name: 'Hey Arnold', image: 'https://upload.wikimedia.org/wikipedia/en/4/45/Arnold_Shortman.png' },
  { name: 'Helga G. Pataki', image: 'https://upload.wikimedia.org/wikipedia/en/6/65/Helga_Pataki.png' },
  { name: 'Sergio Ramos', image: 'https://upload.wikimedia.org/wikipedia/commons/8/88/Sergio_Ramos_2019.jpg' },
  { name: 'Adolf Hitler', image: 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Hitler_portrait_crop.jpg' },
  { name: 'Bad Bunny', image: 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Bad_Bunny_2019_by_Glenn_Francis.jpg' },
  { name: 'Shakira', image: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Shakira_2023.jpg' },
  { name: 'Buzz Lightyear', image: 'https://upload.wikimedia.org/wikipedia/en/b/b4/Buzz_Lightyear.png' },
  { name: 'Woody', image: 'https://upload.wikimedia.org/wikipedia/en/b/b8/Woody_Toy_Story.png' },
  { name: 'Dwayne "The Rock" Johnson', image: 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Dwayne_Johnson_2%2C_2013.jpg' },
  { name: 'Elsa (Frozen)', image: 'https://upload.wikimedia.org/wikipedia/en/0/05/Elsa_%28Frozen%29.png' },
  { name: 'Simba (El Rey León)', image: 'https://upload.wikimedia.org/wikipedia/en/7/73/Simba_from_The_Lion_King.png' },
  { name: 'Hércules', image: 'https://upload.wikimedia.org/wikipedia/en/b/b4/Hercules_disney_character.png' },
  { name: 'Enrique Peña Nieto', image: 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Enrique_Pe%C3%B1a_Nieto_%28cropped%29.jpg' },
  { name: 'Scarlett Johansson', image: 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Scarlett_Johansson_by_Gage_Skidmore_2_%28cropped%2C_2%29.jpg' },
  { name: 'Chris Hemsworth', image: 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Chris_Hemsworth_by_Gage_Skidmore_2_%28cropped%29.jpg' },
  { name: 'Ryan Reynolds', image: 'https://upload.wikimedia.org/wikipedia/commons/1/14/Ryan_Reynolds_2016.jpg' },
  { name: 'Pedro Pascal', image: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Pedro_Pascal_by_Gage_Skidmore.jpg' },
  { name: 'Angelina Jolie', image: 'https://upload.wikimedia.org/wikipedia/commons/a/ad/Angelina_Jolie_2_June_2014_%28cropped%29.jpg' },
  { name: 'Will Smith', image: 'https://upload.wikimedia.org/wikipedia/commons/3/3f/TechCrunch_Disrupt_2019_%2848834434641%29_%28cropped%29.jpg' },
  { name: 'Sofía Vergara', image: 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Sof%C3%ADa_Vergara_2019.jpg' },
  { name: 'Morgan Freeman', image: 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Morgan_Freeman_Deauville_2018.jpg' },
  { name: 'Jim Carrey', image: 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Jim_Carrey_2008.jpg' },
  { name: 'Ariana Grande', image: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/Ariana_Grande_Grammys_Red_Carpet_2020.png' },
  { name: 'Bruno Mars', image: 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Bruno_Mars_2018_%28cropped%29.jpg' },
  { name: 'Ed Sheeran', image: 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Ed_Sheeran-6886_%28cropped%29.jpg' },
  { name: 'Karol G', image: 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Karol_G_2019.jpg' },
  { name: 'Rihanna', image: 'https://upload.wikimedia.org/wikipedia/commons/c/c2/Rihanna_Fenty_2018.png' },
  { name: 'Beyoncé', image: 'https://upload.wikimedia.org/wikipedia/commons/1/17/Beyonce_-_The_Formation_World_Tour%2C_at_Wembley_Stadium_in_London%2C_England.jpg' },
  { name: 'Peso Pluma', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/300px-No_image_available.svg.png' },
  { name: 'Luis Miguel', image: 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Luis_Miguel_%28cropped%29.jpg' },
  { name: 'LeBron James', image: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/LeBron_James_%2851959977144%29_%28cropped2%29.jpg' },
  { name: 'Canelo Álvarez', image: 'https://upload.wikimedia.org/wikipedia/commons/3/3c/Sa%C3%BAl_%C3%81lvarez_2015.jpg' },
  { name: "Shaquille O'Neal", image: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Shaquille_O%27Neal_2012.jpg' },
  { name: 'Kobe Bryant', image: 'https://upload.wikimedia.org/wikipedia/commons/9/96/Kobe_Bryant_8.jpg' },
  { name: 'Luigi', image: 'https://upload.wikimedia.org/wikipedia/en/f/f1/LuigiNSMBW.png' },
  { name: 'Link (Zelda)', image: 'https://upload.wikimedia.org/wikipedia/en/3/3e/Link_%28The_Legend_of_Zelda%29.png' },
  { name: 'Mulan', image: 'https://upload.wikimedia.org/wikipedia/en/2/twentytwo/Mulan_Disney_character.png' },
  { name: 'Bob Esponja', image: 'https://upload.wikimedia.org/wikipedia/en/3/3b/SpongeBob_SquarePants_character.svg' },
  { name: 'Homero Simpson', image: 'https://upload.wikimedia.org/wikipedia/en/0/02/Homer_Simpson_2006.png' },
  { name: 'Darth Vader', image: 'https://upload.wikimedia.org/wikipedia/en/7/76/Darth_Vader.jpg' },
  { name: 'Zinedine Zidane', image: 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Zinedine_Zidane_by_Tasnim_03.jpg' },
  { name: 'Leonardo DiCaprio', image: 'https://upload.wikimedia.org/wikipedia/commons/4/46/Leonardo_Dicaprio_Cannes_2019.jpg' },
  { name: 'Anne Hathaway', image: 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Anne_Hathaway_in_2017.jpg' },
  { name: 'Lady Gaga', image: 'https://upload.wikimedia.org/wikipedia/commons/7/79/Lady_Gaga_at_Joe_Biden%27s_inauguration_%28cropped_3%29.jpg' },
  { name: 'Rafael Nadal', image: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Rafael_Nadal_10%2C_Aegon_Championships%2C_London%2C_UK_-_Diliff_%28cropped%29.jpg' },
  { name: 'Novak Djokovic', image: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Novak_Djokovic_Trophy_Wimbledon_2019-croped_and_edited.jpg' },
  { name: 'Jeff Bezos', image: 'https://upload.wikimedia.org/wikipedia/commons/0/03/Jeff_Bezos_visits_LAAFB_SMC_%283908618%29_%28cropped%29.jpeg' },
  { name: 'Tim Cook', image: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Tim_Cook_2009_cropped.jpg' },
  { name: 'Ratatouille', image: 'https://upload.wikimedia.org/wikipedia/en/5/50/RatatouillePoster.jpg' },
  { name: 'Rocky Balboa', image: 'https://upload.wikimedia.org/wikipedia/en/1/1f/Rocky_Balboa_%28character%29.jpg' }
];